development:
  adapter: mysql
  encoding: utf8
  database: user_auth_development
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  encoding: utf8
  database: user_auth_test
  username: root
  password: root
  pool: 5
  timeout: 5000


production:
  adapter: mysql
  encoding: utf8
  database: user_auth_0531
  username: root
  password: root
  pool: 5
  timeout: 5000