development:
  name: user_auth
  url: http://192.168.1.8:3001/
  master_url: http://192.168.1.8:3000/
  user_logo_file_path_root: /root/mindpin_base/mindpin_education_files/
  user_logo_file_url_root: http://img.edu.mindpin.com/

test:
  name: user_auth
  url: http://192.168.1.8:3001/
  master_url: http://192.168.1.8:3000/
  user_logo_file_path_root: /root/mindpin_base/mindpin_education_files/
  user_logo_file_url_root: http://img.edu.mindpin.com/

production:
  name: user_auth
  url: http://2010.mindpin.com/
  master_url: http://2010.mindpin.com/config
  user_logo_file_path_root: /root/mindpin_base/mindpin_education_files/
  user_logo_file_url_root: http://img.edu.mindpin.com/
